import { ExperienceType, LanguageType } from "../types/common";

const experiencesEN = [
  {
    id: 1,
    position: "Full-Stack Developer",
    company: "WEMANITY",
    client: "EMERGA",
    period: "October 2024 to present",
    location: "",
    context:
      "EmerGa is a general interest association that develops innovative projects in the field of emergency medicine. We are working on the development of a mobile application that helps save lives: our application helps citizens provide assistance and facilitates exchanges between witnesses and emergency services.",
    responsibilities: [
      "Design and development of a video call component using the Twilio Video API",
      "Implementation of essential features such as audio/video stream management, virtual conference rooms, and interactive user interface",
      "Deployment and maintenance on development and pre-production environments",
      "Bug resolution and continuous improvement of code quality",
      "Optimized management of data flows between client and server",
      "Integration of APIs in the front-end application",
    ],
    technical_environment: [
      "React JS",
      "TypeScript",
      "JavaScript",
      "Express Js",
      "Git",
      "AWS",
      "MySQL",
      "Sequelize",
      "VScode",
      "Github",
      "Postman",
      "Twilio",
    ],
  },
  {
    id: 2,
    position: "Back-End Developer",
    company: "WEMANITY",
    client: "ADEO",
    period: "July 2024 to September 2024",
    location: "",
    context:
      "An ambitious project aimed at digitizing and automating all user journeys (sellers, craftsmen, customers) through digital tools. Primarily focused on managing the network of partner craftsmen, from sourcing to onboarding, as well as partnership management, the project was part of an agile approach. The multidisciplinary team, composed of a tech lead, three developers, a project manager, a QA, and a designer, operated according to agile principles with regular sprints, planning sessions, reviews, and retrospectives.",
    responsibilities: [
      "Development of APIs for data reading and extraction",
      "Implementation of Kafka consumers to retrieve data",
      "Implementation of Kafka producers to publish data",
      "Writing and executing unit tests and integration tests",
      "Participation in sprint planning and backlog grooming sessions",
      "Code review to ensure compliance with standards and best practices",
      "Deployment of applications to different environments",
      "Extension of the data model to meet new project requirements",
      "Creation and management of database migration requests with Flyway",
    ],
    technical_environment: [
      "Java",
      "Springboot",
      "Spring-configuration",
      "Spring-Web",
      "Junit",
      "Kafka",
      "Nest",
      "TypeScript",
      "Jest",
      "Git",
      "Github",
      "Turbine",
      "Kubernetes",
      "Vault",
      "Phrase",
      "PostgreSQL",
      "DBeaver",
    ],
  },
  {
    id: 3,
    position: "Full-Stack Developer",
    company: "WEMANITY",
    client: "DECATHLON",
    period: "October 2022 to March 2024",
    location: "",
    context:
      "A Layout Catalog web application, integrated into the MyBusiness platform, is a B2B sales platform dedicated to Decathlon merchandise for purchasing store layouts and products. This website offers a wide range of products and solutions specifically designed for retail space arrangement, including shelving, displays, and other essential equipment to optimize layout. Designed to facilitate and optimize purchases for industry professionals, this site combines practicality, efficiency, and quality, while being seamlessly integrated into Decathlon's MyBusiness ecosystem.",
    responsibilities: [
      "Integration of designs and mockups into code",
      "Optimization of front-end performance and responsiveness",
      "Development of APIs to enable communication between front-end and back-end",
      "Participation in team meetings and code reviews",
      "Writing and executing unit tests and integration tests",
      "Debugging errors and code-related issues",
      "Deployment of the application to different environments (test, preprod, prod)",
      "Continuous maintenance, update management, and post-deployment problem resolution",
      "Creation and management of database migration requests with Flyway",
    ],
    technical_environment: [
      "React JS",
      "TypeScript",
      "JavaScript",
      "Java",
      "Spring Boot",
      "Jenkins",
      "Git",
      "Kubernetes",
      "Vault",
      "Phrase",
      "PostgreSQL",
      "DBeaver",
      "VScode",
      "Intellij IDEA",
      "Github",
      "Postman",
      "Jira",
      "Slack",
    ],
  },
  {
    id: 4,
    position: "Full-Stack Developer (Final Year Project)",
    company: "ASFOTEC",
    period: "April 2022 - September 2022",
    location: "Mons-en-Barœul, France",
    context:
      "Web application to create questionnaires and send them to candidates to evaluate their skills.",
    responsibilities: [
      "Redesign of the project architecture (back-end and front-end)",
      "Development of web components",
      "Development of REST APIs",
      "Integration of designs and mockups into code",
      "Optimization of front-end performance and responsiveness",
      "Participation in team meetings and code reviews",
      "Debugging errors and code-related issues",
    ],
    technical_environment: [
      "Express.js",
      "Firebase",
      "TypeScript",
      "React js",
      "Redux",
      "Sagas",
      "MUI",
      "MongoDB",
      "GitHub",
      "Postman",
      "Scrum",
      "Notion",
    ],
  },
  {
    id: 5,
    position: "Full-Stack Developer",
    company: "TAILLISLABS",
    client: "BMCI",
    period: "June 2020 to August 2021",
    location: "Casablanca, Morocco",
    context:
      "Contribution with the Taillis team in an external mission at a client in the banking sector (BOA) to manage the web part (Front-End) of their website.",
    responsibilities: [
      "Implementation of a credit simulator (back-office / front-office)",
      "Management of the front-office part of the website for the BOA client",
      "Development of web components",
      "Development of REST APIs",
      "Integration of APIs",
      "Writing unit tests",
      "Integration of designs and mockups into code",
      "Management of the application store",
    ],
    technical_environment: [
      "React js",
      "Hooks",
      "Context",
      "Ant design",
      "Express",
      "PostgreSQL",
      "Redux",
      "Saga",
      "Bitbucket",
      "Scrum",
      "Jira",
      "Slack",
    ],
  },
  {
    id: 6,
    position: "Full-Stack Developer",
    company: "TAILLISLABS",
    client: "AUTOPLUS",
    period: "November 2019 to May 2020",
    location: "Casablanca, Morocco",
    context:
      "Contribution to a development project for a website and mobile application (B2B) for online purchase of automobile parts for the client AutoPlus.",
    responsibilities: [
      "Implementation of a microservice architecture",
      "Development of a layer that communicates with and receives data from the Tecalliance API",
      "Development of a synchronization layer between the client's internal database and our database",
      "Development of GraphQL APIs",
      "Development of web and mobile components",
      "Integration of designs and mockups into code",
    ],
    technical_environment: [
      "Express.js",
      "GraphQL",
      "React js",
      "React native",
      "PostgreSQL",
      "TypeORM",
      "GitLab",
      "Postman",
      "Kafka",
      "Scrum",
      "Jira",
      "Slack",
    ],
  },
  {
    id: 7,
    position: "Full-Stack Developer (Final Year Project)",
    company: "ALPHALUPI TECH",
    period: "February 2019 to July 2019",
    location: "Casablanca, Morocco",
    context:
      "Implementation of an intelligent platform for communication between bank employees (BMCI) based on a chatbot and navigation interfaces: A collaborative HR intranet platform for the administration of bank communications. A mobile application that gives all employees access to intranet content through communication interfaces, FAQs, a notification system, and an intelligent assistant.",
    responsibilities: [
      "Development of the collaborative HR intranet platform",
      "Development of the mobile application for intranet content access",
      "Implementation of communication interfaces and FAQs",
      "Integration of a notification system",
      "Development of an intelligent assistant",
    ],
    technical_environment: [
      "Java",
      "Spring boot",
      "AWS S3",
      "Mobile Push (OneSignal)",
      "TypeScript",
      "React js",
      "React Native",
      "Git",
      "PostgreSQL",
      "JUnit",
      "Postman",
      "Scrum",
      "Jira",
      "Slack",
    ],
  },
];

const experiencesFR = [
  {
    id: 1,
    poste: "Développeur Full-Stack",
    entreprise: "WEMANITY",
    client: "EMERGA",
    periode: "Octobre 2024 jusqu'au présent",
    lieu: "",
    contexte:
      "EmerGa est une association d'intérêt général qui développe des projets innovants dans le domaine de la médecine d'urgence. Nous travaillons sur le développement d'une application mobile qui permet de sauver des vies : notre application aide les citoyens à porter secours et facilite les échanges entre témoins et services de secours.",
    responsabilites: [
      "Conception et développement d'un composant d'appels vidéo utilisant l'API Twilio Video",
      "Implémentation des fonctionnalités essentielles telles que la gestion des flux audio/vidéo, les salles de conférence virtuelles et l'interface utilisateur interactive",
      "Déploiement et maintenance sur les environnements de développement et pré-production",
      "Résolution de bugs et amélioration continue de la qualité du code",
      "Gestion optimisée des flux de données entre le client et le serveur",
      "Intégration des APIs dans l'application front-end",
    ],
    environnement_technique: [
      "React JS",
      "TypeScript",
      "JavaScript",
      "Express Js",
      "Git",
      "AWS",
      "MySQL",
      "Sequelize",
      "VScode",
      "Github",
      "Postman",
      "Twilio"
    ],
  },
  {
    id: 2,
    poste: "Développeur Back-End",
    client: "ADEO",
    entreprise: "WEMANITY",
    periode: "Juillet 2024 à septembre 2024",
    lieu: "",
    contexte:
      "Un projet ambitieux avait pour objectif de digitaliser et automatiser l'ensemble des parcours des différents utilisateurs (vendeurs, artisans, clients) via des outils numériques. Principalement axé sur la gestion du réseau d'artisans partenaires, de leur sourcing à leur onboarding, ainsi que la gestion des partenariats, le projet s'inscrivait dans une démarche agile. L'équipe multidisciplinaire, composée d'un tech lead, de trois développeurs, d'un chef de projet, d'un QA et d'un designer, fonctionnait selon les principes agiles avec des sprints réguliers, des sessions de planification, des revues et des rétrospectives.",
    responsabilites: [
      "Développement d'API pour la lecture et extraction des données",
      "Mise en place des consumers Kafka pour récupérer les données",
      "Mise en place des producers Kafka pour publier les données",
      "Rédaction et exécution de tests unitaires et tests d'intégration",
      "Participation aux sprints planning et aux sessions de backlog grooming",
      "Revue de code pour assurer la conformité aux standards et bonnes pratiques",
      "Déploiement des applications sur différents environnements",
      "Extension du modèle de données pour répondre aux nouvelles exigences du projet",
      "Création et gestion de requêtes de migration de base de données avec Flyway",
    ],
    environnement_technique: [
      "Java",
      "Springboot 3",
      "Spring-configuration",
      "Spring-Web",
      "Junit",
      "Kafka",
      "Nest",
      "TypeScript",
      "Jest",
      "Git",
      "Github",
      "Turbine",
      "Kubernetes",
      "Vault",
      "Phrase",
      "PostgreSQL",
      "DBeaver",
    ],
  },
  {
    id: 3,
    poste: "Développeur Full Stack",
    entreprise: "WEMANITY",
    client: "DECATHLON",
    periode: "Octobre 2022 à mars 2024",
    lieu: "",
    contexte:
      "Une application web Catalogue Agencement, intégrée à la plateforme MyBusiness, est une plateforme de vente B2B dédiée aux merch de Decathlon pour l'achat des agencements et produits des magasins. Ce site web offre une vaste gamme de produits et de solutions spécialement conçus pour l'aménagement des espaces de vente, y compris les rayonnages, les présentoirs, et d'autres équipements essentiels pour optimiser l'agencement. Conçu pour faciliter et optimiser les achats pour les professionnels du secteur, ce site allie praticité, efficacité, et qualité, tout en étant intégré harmonieusement dans l'écosystème MyBusiness de Decathlon.",
    responsabilites: [
      "Intégration de designs et de maquettes dans le code",
      "Optimisation de la performance et de la réactivité du front-end",
      "Développement d'API pour permettre la communication entre le front-end et le back-end",
      "Participation aux réunions d'équipe et aux revues de code",
      "Rédaction et exécution de tests unitaires et tests d'intégration",
      "Débogage des erreurs et des problèmes liés au code",
      "Déploiement de l'application sur les different environnement (test, preprod, prod)",
      "Maintenance continue, gestion des mises à jour et résolution des problèmes post-déploiement",
      "Création et gestion de requêtes de migration de base de données avec Flyway",
    ],
    environnement_technique: [
      "React JS",
      "TypeScript",
      "JavaScript",
      "Java",
      "Spring Boot",
      "Jenkins",
      "Git",
      "Kubernetes",
      "Vault",
      "Phrase",
      "PostgreSQL",
      "DBeaver",
      "VScode",
      "Intellij IDEA",
      "Github",
      "Postman",
      "Jira",
      "Slack",
    ],
  },
  {
    id: 4,
    poste: "Développeur Full-Stack (PFE)",
    entreprise: "ASFOTEC",
    periode: "Avril 2022 - septembre 2022",
    lieu: "Mons-en-Barœul, France",
    contexte:
      "Application web pour créer des questionnaires et l'envoyer aux candidats pour évaluer leurs compétences.",
    responsabilites: [
      "La refonte de l'architecture de projet (back-end et front-end)",
      "Développement des Composants web",
      "Développement des API's REST",
      "Intégration de designs et de maquettes dans le code",
      "Optimisation de la performance et de la réactivité du front-end",
      "Participation aux réunions d'équipe et aux revues de code",
      "Débogage des erreurs et des problèmes liés au code",
    ],
    environnement_technique: [
      "Express.js",
      "Firebase",
      "TypeScript",
      "React js",
      "Redux",
      "Sagas",
      "MUI",
      "MongoDB",
      "GitHub",
      "Postman",
      "Scrum",
      "Notion",
    ],
  },
  {
    id: 5,
    poste: "Développeur Full-Stack",
    entreprise: "TAILLISLABS",
    client: "BANK OF AFRICA",
    periode: "Juin 2020 jusqu'à Août 2021",
    lieu: "Casablanca, Maroc",
    contexte:
      "Contribution avec l'équipe Taillis dans une mission externe chez un client dans le secteur bancaire (BOA) pour gérer la partie web (Front-End) de son site web.",
    responsabilites: [
      "Mise en place d'un simulateur de crédit (back-office / front-office)",
      "Gestion de la partie Front-office de site web pour le client BOA",
      "Développement des composants web",
      "Développement des API's Rest",
      "Intégrations des API's",
      "Écriture des Tests unitaires",
      "Intégration de designs et de maquettes dans le code",
      "Gestion du store de l'application",
    ],
    environnement_technique: [
      "React js",
      "Hooks",
      "Context",
      "Ant design",
      "Express",
      "PostgreSQL",
      "Redux",
      "Saga",
      "Bitbucket",
      "Scrum",
      "Jira",
      "Slack",
    ],
  },
  {
    id: 6,
    poste: "Développeur Full-Stack",
    entreprise: "TAILLISLABS",
    client: "AUTOPLUS",
    periode: "November 2019 jusqu'au may 2020",
    lieu: "Casablanca, Maroc",
    contexte:
      "Contribution dans un projet de développement d'un site web et une application mobile (B2B) d'achat en ligne des pièces d'automobile pour le client AutoPlus.",
    responsabilites: [
      "Mise en place d'une architecture micro-service",
      "Développement d'une couche qui communique et reçoit les données de l'api Tecalliance",
      "Développement d'une couche de synchronisation de la base de données interne du client avec notre base de données",
      "Développement des API's Graphql",
      "Développement des Composants web et mobile",
      "Intégration de designs et de maquettes dans le code",
    ],
    environnement_technique: [
      "Express.js",
      "Graphql",
      "React js",
      "React native",
      "PostgreSQL",
      "TypeORM",
      "GitLab",
      "Postman",
      "Kafka",
      "Scrum",
      "Jira",
      "Slack",
    ],
  },
  {
    id: 7,
    poste: "Développeur Full-Stack (PFE)",
    entreprise: "ALPHALUPI TECH",
    client: "BMCI",
    periode: "Février 2019 jusqu'à Juillet 2019",
    lieu: "Casablanca, Maroc",
    contexte:
      "Mise en place d'une plateforme intelligente pour la communication entre les collaborateurs de la banque (BMCI) basée sur un chatbot et des interfaces de navigation: Une plateforme intranet RH collaborative pour l'administration des communications de la banque. Une application mobile qui donne accès à l'ensemble des collaborateurs au contenu intranet à travers des interfaces de communications, FAQs, un système de notification, et un assistant intelligent.",
    responsabilites: [
      "Développement de la plateforme intranet RH collaborative",
      "Développement de l'application mobile pour accès au contenu intranet",
      "Mise en place d'interfaces de communications et FAQs",
      "Intégration d'un système de notification",
      "Développement d'un assistant intelligent",
    ],
    environnement_technique: [
      "Java",
      "Spring boot",
      "AWS S3",
      "Mobile Push (OneSignal)",
      "TypeScript",
      "React js",
      "React Native",
      "Git",
      "PostgreSQL",
      "JUnit",
      "Postman",
      "Scrum",
      "Jira",
      "Slack",
    ],
  },
];

export const getExperiences = (language: LanguageType): ExperienceType[] => {
  return experiencesEN.map((exp, index) => {
    const frExp = experiencesFR[index];

    return {
      id: exp.id,
      title: {
        fr: frExp.poste,
        en: exp.position,
      },
      company: exp.company,
      client: exp.client,
      period: {
        fr: frExp.periode,
        en: exp.period,
      },
      location: {
        fr: frExp.lieu,
        en: exp.location,
      },
      context: {
        fr: frExp.contexte,
        en: exp.context,
      },
      responsibilities: {
        fr: frExp.responsabilites,
        en: exp.responsibilities,
      },
      technical_environment: exp.technical_environment,
      description: {
        fr:
          frExp.contexte.substring(0, 150) +
          (frExp.contexte.length > 150 ? "..." : ""),
        en:
          exp.context.substring(0, 150) +
          (exp.context.length > 150 ? "..." : ""),
      },
    };
  });
};

export default getExperiences;
